package com.brayanvanz.park_api.controllers;

import java.net.URI;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort.Direction;
import org.springframework.data.web.PageableDefault;
import org.springframework.http.HttpHeaders;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

import com.brayanvanz.park_api.dtos.PageableDto;
import com.brayanvanz.park_api.dtos.ParkingResponseDto;
import com.brayanvanz.park_api.dtos.ParkingSaveDto;
import com.brayanvanz.park_api.dtos.mappers.ClientParkingSpaceMapper;
import com.brayanvanz.park_api.dtos.mappers.PageableMapper;
import com.brayanvanz.park_api.entities.ClientParkingSpace;
import com.brayanvanz.park_api.exceptions.ErrorMessage;
import com.brayanvanz.park_api.jwt.JwtUserDetails;
import com.brayanvanz.park_api.repositories.projections.ClientParkingSpaceProjection;
import com.brayanvanz.park_api.services.ClientParkingSpaceService;
import com.brayanvanz.park_api.services.ParkingService;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.headers.Header;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;

@Tag(name = "Parkings", description = "Performs vehicle check-in and check-out")
@RequiredArgsConstructor
@RestController
@RequestMapping("/api/v1/parkings")
public class ParkingController {

    private final ParkingService parkingService;
    private final ClientParkingSpaceService clientParkingSpaceService;
    
    @Operation(summary = "Check-in operation", description = "Resource used to enter a vehicle into a parking space. " +
        "Requires a bearer token. Access restricted to ADMIN level users", 
        security = @SecurityRequirement(name = "security"),
        responses = {
            @ApiResponse(responseCode = "201", description = "Resource created successfully", 
                headers = @Header(name = HttpHeaders.LOCATION, description = "Created resource URL"),
                content = @Content(mediaType = "application/json", schema = @Schema(implementation = ParkingResponseDto.class))),
            @ApiResponse(responseCode = "403", description = "Resource not available to CLIENT level users",
                content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorMessage.class))),
            @ApiResponse(responseCode = "404", description = "Possible causes: <br/>" +
                "- Client CPF not registered within the system; <br/>" +
                "- No available parking space was found; <br/>",
                content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorMessage.class))),
            @ApiResponse(responseCode = "422", description = "Invalid input data",
                content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorMessage.class)))
        }
    )
    @PostMapping("/check-in")
    @PreAuthorize("hasAuthority('ADMIN')")
    public ResponseEntity<ParkingResponseDto> checkIn(@RequestBody @Valid ParkingSaveDto dto) {
        ClientParkingSpace clientParkingSpace = ClientParkingSpaceMapper.toClientParkingSpace(dto);
        parkingService.checkIn(clientParkingSpace);
        ParkingResponseDto responseDto = ClientParkingSpaceMapper.tDto(clientParkingSpace);
        URI location = ServletUriComponentsBuilder
            .fromCurrentRequestUri().path("/{receipt}")
            .buildAndExpand(clientParkingSpace.getReceipt())
            .toUri();
        
        return ResponseEntity.created(location).body(responseDto);
    }

    @Operation(summary = "Find a parked vehicle", description = "Resource used to find a parked vehicle by its receipt number. " +
        "Requires a bearer token.", 
        security = @SecurityRequirement(name = "security"),
        parameters = {
            @Parameter(in = ParameterIn.PATH, name = "receipt", description = "Receipt number generated by check-in")
        },
        responses = {
            @ApiResponse(responseCode = "200", description = "Resource retrieved successfully", 
                headers = @Header(name = HttpHeaders.LOCATION, description = "Created resource URL"),
                content = @Content(mediaType = "application/json", schema = @Schema(implementation = ParkingResponseDto.class))),
            @ApiResponse(responseCode = "404", description = "Receipt number not found",
                content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorMessage.class))),
        }
    )
    @GetMapping("/check-in/{receipt}")
    @PreAuthorize("hasAnyAuthority('ADMIN', 'CLIENT')")
    public ResponseEntity<ParkingResponseDto> findByReceipt(@PathVariable String receipt) {
        ClientParkingSpace clientParkingSpace = clientParkingSpaceService.findByReceipt(receipt);
        ParkingResponseDto dto = ClientParkingSpaceMapper.tDto(clientParkingSpace);

        return ResponseEntity.ok(dto);
    }

    @Operation(summary = "Check-out operation", description = "Resource used to remove a vehicle from a parking space. " +
        "Requires a bearer token. Access restricted to ADMIN level users", 
        security = @SecurityRequirement(name = "security"),
        parameters = {
            @Parameter(in = ParameterIn.PATH, name = "receipt", description = "Receipt number generated by check-in")
        },
        responses = {
            @ApiResponse(responseCode = "201", description = "Resource updated successfully", 
                content = @Content(mediaType = "application/json", schema = @Schema(implementation = ParkingResponseDto.class))),
            @ApiResponse(responseCode = "403", description = "Resource not available to CLIENT level users",
                content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorMessage.class))),
            @ApiResponse(responseCode = "404", description = "Possible causes: <br/>" +
                "- Receipt number not available; <br/>" +
                "- Vehicle already checked-out; <br/>",
                content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorMessage.class)))
        }
    )
    @PutMapping("/check-out/{receipt}")
    @PreAuthorize("hasAuthority('ADMIN')")
    public ResponseEntity<ParkingResponseDto> checkOut(@PathVariable String receipt) {
        ClientParkingSpace clientParkingSpace = parkingService.checkOut(receipt);
        ParkingResponseDto dto = ClientParkingSpaceMapper.tDto(clientParkingSpace);

        return ResponseEntity.ok(dto);
    }
    
    @Operation(summary = "Find all parkings by CPF", description = "Resource used to retrieve all parkings from a client by their CPF. " +
        "Requires a bearer token.", 
        security = @SecurityRequirement(name = "security"),
        parameters = {
            @Parameter(in = ParameterIn.PATH, name = "cpf", description = "Client CPF", required = true),
            @Parameter(in = ParameterIn.PATH, name = "page", description = "Page returned", required = true, 
                content = @Content(schema = @Schema(type = "integer", defaultValue = "0"))),
            @Parameter(in = ParameterIn.PATH, name = "size", description = "Total elements per page", required = true,
                content = @Content(schema = @Schema(type = "integer", defaultValue = "5"))),
            @Parameter(in = ParameterIn.PATH, name = "sort", description = "Sorting type 'entryDate,asc'", required = true, 
                content = @Content(schema = @Schema(type = "string", defaultValue = "entryDate,asc"))),
        },
        responses = {
            @ApiResponse(responseCode = "200", description = "Resource retrieved successfully", 
                content = @Content(mediaType = "application/json", schema = @Schema(implementation = PageableDto.class))),
            @ApiResponse(responseCode = "403", description = "Resource not available to CLIENT level users",
                content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorMessage.class)))
        }
    )
    @GetMapping("/cpf/{cpf}")
    @PreAuthorize("hasAuthority('ADMIN')")
    public ResponseEntity<PageableDto<ClientParkingSpaceProjection>> findAllParkingsByCpf(@PathVariable String cpf,
        @PageableDefault(size = 5, sort = "entryDate", direction = Direction.ASC) Pageable pageable) {
        Page<ClientParkingSpaceProjection> projection = clientParkingSpaceService.findAllByClientCpf(cpf, pageable);
        PageableDto<ClientParkingSpaceProjection> dto = PageableMapper.toDto(projection);

        return ResponseEntity.ok(dto);
    }

    @Operation(summary = "Find all parkings of logged in client", description = "Resource used to retrieve all parkings from currently logged in client. " +
        "Requires a bearer token.", 
        security = @SecurityRequirement(name = "security"),
        parameters = {
            @Parameter(in = ParameterIn.PATH, name = "page", description = "Page returned", required = true, 
                content = @Content(schema = @Schema(type = "integer", defaultValue = "0"))),
            @Parameter(in = ParameterIn.PATH, name = "size", description = "Total elements per page", required = true,
                content = @Content(schema = @Schema(type = "integer", defaultValue = "5"))),
            @Parameter(in = ParameterIn.PATH, name = "sort", description = "Sorting type 'entryDate,asc'", required = true, 
                content = @Content(schema = @Schema(type = "string", defaultValue = "entryDate,asc"))),
        },
        responses = {
            @ApiResponse(responseCode = "200", description = "Resource retrieved successfully", 
                content = @Content(mediaType = "application/json", schema = @Schema(implementation = PageableDto.class))),
            @ApiResponse(responseCode = "403", description = "Resource not available to ADMIN level users",
                content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorMessage.class)))
        }
    )
    @GetMapping
    @PreAuthorize("hasAuthority('CLIENT')")
    public ResponseEntity<PageableDto<ClientParkingSpaceProjection>> findAllParkingsClient(@AuthenticationPrincipal JwtUserDetails user,
        @PageableDefault(size = 5, sort = "entryDate", direction = Direction.ASC) Pageable pageable) {
        Page<ClientParkingSpaceProjection> projection = clientParkingSpaceService.findAllByClientUserId(user.getId(), pageable);
        PageableDto<ClientParkingSpaceProjection> dto = PageableMapper.toDto(projection);

        return ResponseEntity.ok(dto);
    }
}
